version: 2.1

jobs:
  detect-changes-and-create-snapshots:
    docker:
      - image: cimg/base:current

    steps:
      # Checkout the code
      - checkout

      # Add SSH keys if needed (use if interacting with private repositories)
      - add_ssh_keys:
          fingerprints:
            - "SHA256:kH2pPODfJX9pp3OGFT/tcw58s7jSxwGzmzl7CRyNBHk"

      # Check if any base.ts file inside integrations/wallets/ was modified and create snapshots if it was
      - run:
          name: Check for Changes in any integrations/wallets/*/base.ts and Create Snapshots
          command: |
            # Fetch the PR changes (ensure we're on the correct branch)
            git fetch origin "${CIRCLE_BRANCH}"

            # Check if any base.ts file inside integrations/wallets/ was modified
            if git diff --name-only origin/main...${CIRCLE_BRANCH} | grep -q "^integrations/wallets/.*base.ts$"; then
              echo "Detected changes in a base.ts file inside integrations/wallets/. Creating snapshots."

              # Create snapshots in e2e/wallets/blockscout/snapshots for each relevant chain
              # Modify this with your logic for which chains need snapshots
              chains=("chain1" "chain2" "chain3") # List of chains to create snapshots for

              for chain in "${chains[@]}"; do
                echo "Creating snapshot for $chain"
                
                # Command to generate snapshot for each chain, assuming you have a script or test setup for this
                # Replace this with your actual snapshot creation logic
                mkdir -p "e2e/wallets/blockscout/snapshots/$chain"
                touch "e2e/wallets/blockscout/snapshots/$chain/snapshot_${chain}.json"
                echo "Snapshot for $chain created."

              done

              # Commit and push the changes
              git config user.email "alannnc@gmail.com"
              git config user.name "CircleCI Job"
              git add README.md
              git commit -m "Append a dot and a new line to README.md [skip ci]"
              git push origin "${CIRCLE_BRANCH}"
              
            else
              echo "No changes detected in any base.ts file inside integrations/wallets/. Skipping snapshot creation."
            fi

workflows:
  version: 2
  snapshot-workflow:
    jobs:
      - detect-changes-and-create-snapshots
